kube_config_context = "devops-interview"
deployment_yaml     = "manifests/deploy.yaml"
image_name          ="docker.io/edamsoft/turo:4-6d93701"
kube_namespace      = "eric-testing"
acm_arn             = "arn:aws:acm:us-east-1:663118211814:certificate/f77cd7ad-b251-470f-aff3-8a3faa12e4c2"
ssl_service_yaml    = "manifests/https_service.yaml"
display_value       = "Explore the world's largest car sharing marketplace"
